package com.pocsspace.bpmassingsequenceowner;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class doOwners implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Users")
	private java.util.List<com.pocsspace.bpmassingsequenceowner.doUser> users;

	public doOwners() {
	}

	public java.util.List<com.pocsspace.bpmassingsequenceowner.doUser> getUsers() {
		return this.users;
	}

	public void setUsers(
			java.util.List<com.pocsspace.bpmassingsequenceowner.doUser> users) {
		this.users = users;
	}

	public doOwners(
			java.util.List<com.pocsspace.bpmassingsequenceowner.doUser> users) {
		this.users = users;
	}

}